export const DIRECTIONS = {
    NORTH: 0,
    EAST: 16,
    SOUTH: 32,
    WEST: 48
};

export const OPPOSITE_DIRECTIONS = {
    0: DIRECTIONS.SOUTH,
    16: DIRECTIONS.WEST,
    32: DIRECTIONS.NORTH,
    64: DIRECTIONS.EAST
};

export const DIRECTION_ORDER = [DIRECTIONS.NORTH, DIRECTIONS.EAST, DIRECTIONS.SOUTH, DIRECTIONS.WEST];
